# Generated by Django 5.2.8 on 2025-12-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcipientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
            ],
            options={
                'verbose_name': 'Excipient Category',
                'verbose_name_plural': 'Excipient Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Excipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(db_index=True, help_text='The ingredient name as it appears in FDA data', max_length=500)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=200, null=True)),
                ('cas_number', models.CharField(blank=True, max_length=50, null=True)),
                ('unii', models.CharField(blank=True, max_length=50, null=True)),
                ('potency_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('potency_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_daily_exposure', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_daily_exposure_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('common_technical_name', models.CharField(blank=True, max_length=500, null=True)),
                ('common_trade_or_consumer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excipients', to='search.excipientcategory')),
            ],
            options={
                'verbose_name': 'Excipient',
                'verbose_name_plural': 'Excipients',
                'indexes': [models.Index(fields=['ingredient_name'], name='search_exci_ingredi_353311_idx'), models.Index(fields=['category'], name='search_exci_categor_beb534_idx')],
            },
        ),
    ]
